default: &default
  hosts:
    - sure-demo.pikapod.net
    - demo.sure.am
  email: user@example.com
  password: Password1!

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
